pub const NATIVE_FUNCTION_NAMES: &[&str] = &[
    "println",
    "print",
    "read_stdin",
    "read_line",
    "format",
    "type_of",
];

// ── Method & function metadata for LSP completions / hover ──────────────────

pub struct MethodInfo {
    pub receiver_type: &'static str,
    pub name: &'static str,
    pub params: &'static str,
    pub returns: &'static str,
    pub doc: &'static str,
}

pub struct NativeFunctionInfo {
    pub name: &'static str,
    pub params: &'static str,
    pub returns: &'static str,
    pub doc: &'static str,
}

pub const NATIVE_METHODS: &[MethodInfo] = &[
    // ── string ──────────────────────────────────────────────────────────────
    MethodInfo {
        receiver_type: "string",
        name: "len",
        params: "()",
        returns: "number",
        doc: "Returns the character count of the string.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "char_at",
        params: "(index)",
        returns: "string",
        doc: "Returns the character at the given index.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "substring",
        params: "(start, end?)",
        returns: "string",
        doc: "Returns a substring from start to end (or end of string).",
    },
    MethodInfo {
        receiver_type: "string",
        name: "split",
        params: "(delimiter)",
        returns: "array",
        doc: "Splits the string by a delimiter and returns an array.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "lines",
        params: "()",
        returns: "array",
        doc: "Splits the string into lines.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "trim",
        params: "()",
        returns: "string",
        doc: "Removes leading and trailing whitespace.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "contains",
        params: "(substring)",
        returns: "bool",
        doc: "Returns true if the string contains the given substring.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "starts_with",
        params: "(prefix)",
        returns: "bool",
        doc: "Returns true if the string starts with the given prefix.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "ends_with",
        params: "(suffix)",
        returns: "bool",
        doc: "Returns true if the string ends with the given suffix.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "to_num",
        params: "()",
        returns: "number",
        doc: "Parses the string as a number.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "chars",
        params: "()",
        returns: "array",
        doc: "Returns an array of single-character strings.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "replace",
        params: "(old, new)",
        returns: "string",
        doc: "Replaces all occurrences of old with new.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "index_of",
        params: "(substring)",
        returns: "number",
        doc: "Returns the index of the first occurrence, or -1.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "to_upper",
        params: "()",
        returns: "string",
        doc: "Converts the string to uppercase.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "to_lower",
        params: "()",
        returns: "string",
        doc: "Converts the string to lowercase.",
    },
    MethodInfo {
        receiver_type: "string",
        name: "repeat",
        params: "(n)",
        returns: "string",
        doc: "Repeats the string n times.",
    },
    // ── number ──────────────────────────────────────────────────────────────
    MethodInfo {
        receiver_type: "number",
        name: "to_str",
        params: "()",
        returns: "string",
        doc: "Converts the number to a string.",
    },
    MethodInfo {
        receiver_type: "number",
        name: "abs",
        params: "()",
        returns: "number",
        doc: "Returns the absolute value.",
    },
    MethodInfo {
        receiver_type: "number",
        name: "floor",
        params: "()",
        returns: "number",
        doc: "Rounds down to the nearest integer.",
    },
    MethodInfo {
        receiver_type: "number",
        name: "ceil",
        params: "()",
        returns: "number",
        doc: "Rounds up to the nearest integer.",
    },
    MethodInfo {
        receiver_type: "number",
        name: "round",
        params: "()",
        returns: "number",
        doc: "Rounds to the nearest integer.",
    },
    MethodInfo {
        receiver_type: "number",
        name: "pow",
        params: "(exponent)",
        returns: "number",
        doc: "Raises the number to the given power.",
    },
    MethodInfo {
        receiver_type: "number",
        name: "sqrt",
        params: "()",
        returns: "number",
        doc: "Returns the square root.",
    },
    MethodInfo {
        receiver_type: "number",
        name: "floor_div",
        params: "(divisor)",
        returns: "number",
        doc: "Returns the floor of integer division.",
    },
    // ── bool ────────────────────────────────────────────────────────────────
    MethodInfo {
        receiver_type: "bool",
        name: "to_str",
        params: "()",
        returns: "string",
        doc: "Converts the boolean to a string.",
    },
    // ── array ───────────────────────────────────────────────────────────────
    MethodInfo {
        receiver_type: "array",
        name: "enumerate",
        params: "()",
        returns: "array",
        doc: "Returns an array of [index, value] pairs.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "len",
        params: "()",
        returns: "number",
        doc: "Returns the number of elements.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "get",
        params: "(index)",
        returns: "any",
        doc: "Returns the element at the given index.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "first",
        params: "()",
        returns: "any",
        doc: "Returns the first element, or null.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "last",
        params: "()",
        returns: "any",
        doc: "Returns the last element, or null.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "push",
        params: "(value)",
        returns: "null",
        doc: "Appends a value to the end of the array.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "pop",
        params: "()",
        returns: "any",
        doc: "Removes and returns the last element.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "set",
        params: "(index, value)",
        returns: "null",
        doc: "Replaces the element at the given index.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "remove",
        params: "(index)",
        returns: "any",
        doc: "Removes and returns the element at the given index.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "contains",
        params: "(value)",
        returns: "bool",
        doc: "Returns true if the array contains the value.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "reverse",
        params: "()",
        returns: "array",
        doc: "Returns a new reversed array.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "is_empty",
        params: "()",
        returns: "bool",
        doc: "Returns true if the array has no elements.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "join",
        params: "(separator?)",
        returns: "string",
        doc: "Joins elements into a string with an optional separator.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "sum",
        params: "()",
        returns: "number",
        doc: "Returns the sum of all numeric elements.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "min",
        params: "()",
        returns: "number",
        doc: "Returns the smallest numeric element.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "max",
        params: "()",
        returns: "number",
        doc: "Returns the largest numeric element.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "sort",
        params: "()",
        returns: "array",
        doc: "Returns a new sorted array (numbers or strings).",
    },
    MethodInfo {
        receiver_type: "array",
        name: "slice",
        params: "(start, end?)",
        returns: "array",
        doc: "Returns a sub-array from start to end.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "index_of",
        params: "(value)",
        returns: "number",
        doc: "Returns the index of the first match, or -1.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "flatten",
        params: "()",
        returns: "array",
        doc: "Flattens nested arrays by one level.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "zip",
        params: "(other)",
        returns: "array",
        doc: "Zips two arrays into an array of pairs.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "chunk",
        params: "(n)",
        returns: "array",
        doc: "Splits the array into chunks of size n.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "take",
        params: "(n)",
        returns: "array",
        doc: "Returns the first n elements.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "skip",
        params: "(n)",
        returns: "array",
        doc: "Returns all elements after the first n.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "insert",
        params: "(index, value)",
        returns: "null",
        doc: "Inserts a value at the given index.",
    },
    MethodInfo {
        receiver_type: "array",
        name: "swap",
        params: "(i, j)",
        returns: "null",
        doc: "Swaps the elements at indices i and j.",
    },
    // ── map ─────────────────────────────────────────────────────────────────
    MethodInfo {
        receiver_type: "map",
        name: "get",
        params: "(key)",
        returns: "any",
        doc: "Returns the value for the given key, or null.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "get_or",
        params: "(key, default)",
        returns: "any",
        doc: "Returns the value for key, or the default.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "set",
        params: "(key, value)",
        returns: "null",
        doc: "Sets a key-value pair in the map.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "has",
        params: "(key)",
        returns: "bool",
        doc: "Returns true if the map contains the key.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "remove",
        params: "(key)",
        returns: "any",
        doc: "Removes and returns the value for the given key.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "keys",
        params: "()",
        returns: "array",
        doc: "Returns an array of all keys.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "values",
        params: "()",
        returns: "array",
        doc: "Returns an array of all values.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "entries",
        params: "()",
        returns: "array",
        doc: "Returns an array of [key, value] pairs.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "len",
        params: "()",
        returns: "number",
        doc: "Returns the number of entries.",
    },
    MethodInfo {
        receiver_type: "map",
        name: "is_empty",
        params: "()",
        returns: "bool",
        doc: "Returns true if the map has no entries.",
    },
    // ── range ───────────────────────────────────────────────────────────────
    MethodInfo {
        receiver_type: "range",
        name: "from",
        params: "()",
        returns: "number",
        doc: "Returns the start of the range.",
    },
    MethodInfo {
        receiver_type: "range",
        name: "until",
        params: "()",
        returns: "number",
        doc: "Returns the end of the range (exclusive).",
    },
    MethodInfo {
        receiver_type: "range",
        name: "to_array",
        params: "()",
        returns: "array",
        doc: "Converts the range to an array of numbers.",
    },
];

pub const NATIVE_FUNCTIONS_INFO: &[NativeFunctionInfo] = &[
    NativeFunctionInfo {
        name: "println",
        params: "(value)",
        returns: "null",
        doc: "Prints a value followed by a newline.",
    },
    NativeFunctionInfo {
        name: "print",
        params: "(value)",
        returns: "null",
        doc: "Prints a value without a trailing newline.",
    },
    NativeFunctionInfo {
        name: "read_stdin",
        params: "()",
        returns: "string",
        doc: "Reads all of stdin as a string.",
    },
    NativeFunctionInfo {
        name: "read_line",
        params: "()",
        returns: "string",
        doc: "Reads a single line from stdin.",
    },
    NativeFunctionInfo {
        name: "format",
        params: "(template, ...args)",
        returns: "string",
        doc: "Formats a string with {} placeholders.",
    },
    NativeFunctionInfo {
        name: "type_of",
        params: "(value)",
        returns: "string",
        doc: "Returns the type name of a value.",
    },
];

pub const STANDARD_MODULES: &[&str] = &["math", "fs", "sys"];
